apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi
  labels:
    app: fastapi-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: 754874159206.dkr.ecr.ap-northeast-2.amazonaws.com/takeit/fastapi
    argocd-image-updater.argoproj.io/image-update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/allow-tags: '^[a-f0-9]{40}$'
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-commit-message-appendix: '[auto-image-update]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: 754874159206.dkr.ecr.ap-northeast-2.amazonaws.com/takeit/fastapi:latest
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: openai-api-key
