apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: spring
  labels:
    app: spring-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: 754874159206.dkr.ecr.ap-northeast-2.amazonaws.com/takeit/spring
    argocd-image-updater.argoproj.io/image-update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/allow-tags: '^[a-f0-9]{40}$'
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-commit-message-appendix: '[auto-image-update]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container
          image: 754874159206.dkr.ecr.ap-northeast-2.amazonaws.com/takeit/spring:latest
          ports:
            - containerPort: 9800
          env:
            # 🔐 FASTAPI
            - name: FAST_API_URL
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: FAST_API_URL
            # 🔐 MYSQL
            - name: MYSQL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: MYSQL_ENDPOINT
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: MYSQL_PORT
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_NAME
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: MYSQL_NAME

            # 🔐 KAKAO
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: KAKAO_REDIRECT_URI

            # 🔐 GOOGLE
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: GOOGLE_REDIRECT_URI

            # 🔐 NAVER
            - name: NAVER_REQUEST_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: NAVER_REQUEST_TOKEN_URI
            - name: NAVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: NAVER_CLIENT_ID
            - name: NAVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: NAVER_SECRET
            - name: NAVER_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: NAVER_REDIRECT_URI
            - name: NAVER_USER_INFO_URI
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: NAVER_USER_INFO_URI

            # 🔐 REDIS
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: SPRING_REDIS_PORT

            # 🔐 CLIENT_BASE_URL
            - name: CLIENT_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: CLIENT_BASE_URL