namespace: fastapi

app:
  name: fastapi

image:
  repository: 754874159206.dkr.ecr.ap-northeast-2.amazonaws.com/takeit/fastapi
  tag: "548b494fd45f4cac8231335b9dd0d4af81a9da2a"

env:
  OPENAI_API_KEY : ""
  MONGO_DB_URL : ""
  CHROMA_DB_HOST : ""
  CHROMA_DB_PORT : ""
  KAFKA_BOOTSTRAP_SERVERS : ""

ingress:
  certificateArn: "arn:aws:acm:ap-northeast-2:754874159206:certificate/f41cc5fb-6322-4af7-9da9-d139ebe09fc2"

