apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      annotations:
        admission.datadoghq.com/enabled: "true"
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 9800
              name: http
          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/datadog/apm/library/java/dd-java-agent.jar"