apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "takeit-backend.fullname" . }}
  labels:
    app: {{ include "takeit-backend.name" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    alb.ingress.kubernetes.io/group.name: takeit-group
spec:
  rules:
    - host: api.takeit.academy
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "takeit-backend.fullname" . }}
                port:
                  number: 80
