apiVersion: v1
kind: Service
metadata:
  name: spring
  labels:
    app: spring
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9800
      protocol: TCP
      name: http
  selector:
    app: spring
