apiVersion: v1
kind: Service
metadata:
  name: {{ include "takeit-backend.fullname" . }}
  labels:
    app: {{ include "takeit-backend.name" . }}
    chart: {{ include "takeit-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9800
      protocol: TCP
      name: http
  selector:
    app: {{ include "takeit-backend.name" . }}
    release: {{ .Release.Name }}
